package packages

import "github.com/cpmech/gosl/utl"

func init() {
	Packages["gosl/utl"] = map[string]interface{}{
		"AllFalse":            utl.AllFalse,
		"AllTrue":             utl.AllTrue,
		"Alloc":               utl.Alloc,
		"ArgMinMax":           utl.ArgMinMax,
		"BestSquare":          utl.BestSquare,
		"BestSquareApprox":    utl.BestSquareApprox,
		"Clone":               utl.Clone,
		"Cross3d":             utl.Cross3d,
		"CumSum":              utl.CumSum,
		"Deep2checkSize":      utl.Deep2checkSize,
		"Deep2transpose":      utl.Deep2transpose,
		"Deep3GetInfo":        utl.Deep3GetInfo,
		"Deep3alloc":          utl.Deep3alloc,
		"Deep3checkSize":      utl.Deep3checkSize,
		"Deep3set":            utl.Deep3set,
		"Deep4alloc":          utl.Deep4alloc,
		"Deep4set":            utl.Deep4set,
		"DeserializeDeep2":    utl.DeserializeDeep2,
		"DeserializeDeep3":    utl.DeserializeDeep3,
		"Digits":              utl.Digits,
		"Dot3d":               utl.Dot3d,
		"DurSum":              utl.DurSum,
		"Expon":               utl.Expon,
		"Fill":                utl.Fill,
		"FlipCoin":            utl.FlipCoin,
		"FromFloat64s":        utl.FromFloat64s,
		"FromInts":            utl.FromInts,
		"FromString":          utl.FromString,
		"FromStrings":         utl.FromStrings,
		"GetColumn":           utl.GetColumn,
		"GetCopy":             utl.GetCopy,
		"GetITout":            utl.GetITout,
		"GetMapped":           utl.GetMapped,
		"GetMapped2":          utl.GetMapped2,
		"GetReversed":         utl.GetReversed,
		"GetSorted":           utl.GetSorted,
		"GetStrides":          utl.GetStrides,
		"GtPenalty":           utl.GtPenalty,
		"GtePenalty":          utl.GtePenalty,
		"Iabs":                utl.Iabs,
		"Imax":                utl.Imax,
		"Imin":                utl.Imin,
		"IntAddScalar":        utl.IntAddScalar,
		"IntAlloc":            utl.IntAlloc,
		"IntBoolMapSort":      utl.IntBoolMapSort,
		"IntClone":            utl.IntClone,
		"IntCopy":             utl.IntCopy,
		"IntFill":             utl.IntFill,
		"IntFilter":           utl.IntFilter,
		"IntGetSorted":        utl.IntGetSorted,
		"IntIndexSmall":       utl.IntIndexSmall,
		"IntIntsMapAppend":    utl.IntIntsMapAppend,
		"IntMinMax":           utl.IntMinMax,
		"IntNegOut":           utl.IntNegOut,
		"IntPy":               utl.IntPy,
		"IntRange":            utl.IntRange,
		"IntRange2":           utl.IntRange2,
		"IntRange3":           utl.IntRange3,
		"IntSort3":            utl.IntSort3,
		"IntSort4":            utl.IntSort4,
		"IntUnique":           utl.IntUnique,
		"IntVals":             utl.IntVals,
		"IsPowerOfTwo":        utl.IsPowerOfTwo,
		"L2norm":              utl.L2norm,
		"LinSpace":            utl.LinSpace,
		"LinSpaceOpen":        utl.LinSpaceOpen,
		"Max":                 utl.Max,
		"MeshGrid2d":          utl.MeshGrid2d,
		"MeshGrid2dF":         utl.MeshGrid2dF,
		"MeshGrid2dFG":        utl.MeshGrid2dFG,
		"MeshGrid2dV":         utl.MeshGrid2dV,
		"Min":                 utl.Min,
		"MinMax":              utl.MinMax,
		"NonlinSpace":         utl.NonlinSpace,
		"Ones":                utl.Ones,
		"ParetoFront":         utl.ParetoFront,
		"ParetoMin":           utl.ParetoMin,
		"ParetoMinProb":       utl.ParetoMinProb,
		"PrintDeep3":          utl.PrintDeep3,
		"PrintDeep4":          utl.PrintDeep4,
		"ProbContestSmall":    utl.ProbContestSmall,
		"Qsort":               utl.Qsort,
		"Qsort2":              utl.Qsort2,
		"Scaling":             utl.Scaling,
		"SerializeDeep2":      utl.SerializeDeep2,
		"SerializeDeep3":      utl.SerializeDeep3,
		"Sort3":               utl.Sort3,
		"Sort3Desc":           utl.Sort3Desc,
		"Sort4":               utl.Sort4,
		"SortQuadruples":      utl.SortQuadruples,
		"StrAlloc":            utl.StrAlloc,
		"StrBoolMapSort":      utl.StrBoolMapSort,
		"StrBoolMapSortSplit": utl.StrBoolMapSortSplit,
		"StrFltMapSort":       utl.StrFltMapSort,
		"StrFltMapSortSplit":  utl.StrFltMapSortSplit,
		"StrFltsMapAppend":    utl.StrFltsMapAppend,
		"StrIndexSmall":       utl.StrIndexSmall,
		"StrIntMapSort":       utl.StrIntMapSort,
		"StrIntMapSortSplit":  utl.StrIntMapSortSplit,
		"StrIntsMapAppend":    utl.StrIntsMapAppend,
		"StrVals":             utl.StrVals,
		"Sum":                 utl.Sum,
		"Swap":                utl.Swap,
		"ToStrings":           utl.ToStrings,
		"Vals":                utl.Vals,
		"NewOutputter":        utl.NewOutputter,
		"BuildQuadruples":     utl.BuildQuadruples,
		"OutFcnType":          OutFcnType,
		"Observer":            Observer,
		"ToOutFcnType":        ToOutFcnType,
	}
	PackageTypes["gosl/utl"] = map[string]interface{}{
		"List":          utl.List{},
		"Observable":    utl.Observable{},
		"Outputter":     utl.Outputter{},
		"Quadruple":     utl.Quadruple{},
		"Quadruples":    utl.Quadruples{},
		"QuadruplesByI": utl.QuadruplesByI{},
		"QuadruplesByX": utl.QuadruplesByX{},
		"QuadruplesByY": utl.QuadruplesByY{},
		"QuadruplesByZ": utl.QuadruplesByZ{},
		"SerialList":    utl.SerialList{},
		"Sorter":        utl.Sorter{},
	}
}

func OutFcnType() utl.OutFcnType {
	var temp utl.OutFcnType
	return temp
}

func ToOutFcnType(f func([]float64, float64)) utl.OutFcnType {
	return utl.OutFcnType(f)
}

func Observer() utl.Observer {
	var temp utl.Observer
	return temp
}
